README.md, examples/Ship_stability_with_blocks.html
Also, use library constructor correctly on Stability with Blocks example.
=> Introduce contributing guidelines

build/Vessel.js, build/makeBuild.py, examples/Many_ships_in_configurable_ocean.html, examples/data/ship_specifications/PX121.json, examples/js/Ship3D_v2.js, source/classes/BaseObject.js, source/classes/DerivedObject.js, source/classes/Hull.js, source/classes/JSONSpecObject.js, source/classes/Ship.js, source/classes/ShipState.js, source/classes/ShipState_new.js, source/classes/Structure.js
Very minor changes. More to come.
=> Preparing for fromJSON/toJSON, adding hull/object styles, refactoring Ship3D_v2

examples/Hydrostatics.html, examples/Object_geom.html, examples/Object_weight.html
* Block geometry and visualization
* Block weight
* Hull visualization and hydrostatics
=> Add three simple tutorials

examples/Hydrostatics.html, examples/Object_geom.html
Explain how the visualization is created and the 3D ship is added to it.
=> Explain Three.js visualization in examples

examples/Hydrostatics.html, examples/Load_spec.html, examples/Stability.html
* Load a vessel specification.
* Stability.
=> Create two new examples

build/Vessel.js, build/makeBuild.py, examples/Many_ships_in_regular_ocean.html, examples/Ship_in_regular_ocean.html, examples/Stability.html, examples/data/ship_specifications/PX121.json, examples/data/ship_specifications/barge.json, examples/index.html, examples/js/Regular_ocean.js, examples/make_strip.html, source/classes/Ship.js, source/classes/ShipState.js, source/classes/StateModule.js, source/classes/WaveCreator.js, source/classes/WaveMotion.js
* Add a state handling module, regular wave definition and Jensen motion equation.
* Add examples with regular ocean, regular motion response of a single ship and of multiple ships.
* Minor correction in stability example.
* Minor correction in fuel handling.
=> Various additions

build/Vessel.js, examples/Hull_Weight.html, examples/Many_ships_in_regular_ocean.html, examples/Ship_in_regular_ocean.html, examples/blockCase_compare.html, examples/data/ship_specifications/PX121.json, examples/data/ship_specifications/blockCase.json, examples/index.html, examples/js/weightTestCalc.js, source/classes/Hull.js, source/classes/Ship.js, source/math/interpolation.js, source/math/parametricWeightParsons.js
I inserted four new ways of ship hull estimation weight:
- Parametric Midship Weight (Pratical Ship Design, Watson),
- Quadricubic Method (http://www.mar.ist.utl.pt/mventura/Projecto-Navios-I/EN/SD-1.3.1-Estimation%20Methods.pdf),
- Statical Parametric (http://www.mar.ist.utl.pt/mventura/Projecto-Navios-I/EN/SD-1.3.1-Estimation%20Methods.pdf),
- Inland Parametric Weight Estimation (Jan P. Michalski).
Some of then give us back an strange value, this may happens because of difference between our model and model suitable for the formula. Maybe with access to NTNU library you can find the files sources and therefore further explanation about restrictions and applicability of those formulas.
=> Files with weight estimation

build/Vessel.js, source/classes/Hull.js
=> Changing Vessel.js and Hull.js

examples/WebSiteVessels.html
This is the first version of vessels.js web site based on the https://d3js.org/ example.
=> adding vessels.js web site page

examples/Ship_in_Ocean_dynamical_MooringWave.html, examples/snippets/DynamicalMovement.js, examples/snippets/DynamicalMovementMooringWave.js
=> Fix variable name typo

tools/makeBuild.py
Following https://github.com/shiplab/vesseljs/commit/b61c29d1935eb492b71d74b8f21935d5b96ead38
Since I do not know whether this is Henrique's intention, I did not push the commit to master right away. Please review for merging. (Untested too.)
=> Lower-case vessel object with Vessel as alias

examples/Ship_in_Ocean_dynamical_MooringWave_Parametric.html, examples/snippets/DynamicalMovementMooringWaveParametric.js, examples/snippets/Regular_ocean_final.js
New example: adding/removing mooring lines
=> Parametric Mooring Lines

examples/Ship3D_with_pretty_JSON.html
Add support to color and opacity with Ship3D_v2.
=> Update Ship visualization example

examples/specs/ship_specifications/gunnerus.json
Inserting the JSON for Gunnerus
=> add gunnerus Json File

examples/specs/ship_specifications/gunnerus.json
=> Merge Gunnerus information

examples/specs/ship_specifications/gunnerus.json
Because this example was introduced strictly by me and do not change the main code I took the liberty to merge directly from the dev folder.
=> Inserting Featuare in Epoch Example

index.html
=> Rename the model example

examples/3D_models/GLTF/catamaran_deeper_cutout.glb, examples/3D_models/GLTF/catamaran_side_concept_04_2023.glb, examples/OWT_installation_SFI.html
=> Inserting the OWT SFI example

examples/sea_sick.html
=> Adding Sea Sick Example

index.html
Reverts shiplab/vesseljs#190 to fix briken links
=> Revert "Changing data sources from the main page"
